apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicenow-service
spec:
  selector:
    matchLabels:
      run: servicenow-service
  replicas: 1
  template:
    metadata:
      labels:
        run: servicenow-service
    spec:
      containers:
      - name: servicenow-service
        image: keptncontrib/servicenow-service:0.2.1
        ports:
        - containerPort: 8080
        env:
        - name: EVENTBROKER
          value: 'http://event-broker.keptn.svc.cluster.local/keptn'
      - name: distributor
        image: keptn/distributor:0.7.2
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PUBSUB_URL
            value: 'nats://keptn-nats-cluster'
          - name: PUBSUB_TOPIC
            value: 'sh.keptn.event.problem.open'
          - name: PUBSUB_RECIPIENT
            value: '127.0.0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: servicenow-service
  labels:
    run: servicenow-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: servicenow-service