apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicenow-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: servicenow-service
  replicas: 1
  template:
    metadata:
      labels:
        run: servicenow-service
    spec:
      containers:
      - name: servicenow-service
        image: dynatraceacm/servicenow-service:0.2.0
        ports:
        - containerPort: 8080
        env:
        - name: EVENTBROKER
          value: 'http://event-broker.keptn.svc.cluster.local/keptn'
---
apiVersion: v1
kind: Service
metadata:
  name: servicenow-service
  namespace: keptn
  labels:
    run: servicenow-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: servicenow-service