apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: servicenow-service
  namespace: keptn
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        metadata:
          name: servicenow-builder
          namespace: keptn
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/keptn/servicenow-service.git
              revision: master
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: docker-registry.keptn.svc.cluster.local:5000/keptn/servicenow-service:latest
              - name: DOCKERFILE
                value: /Dockerfile
      revisionTemplate:
        metadata:
        spec:
          container:
            image: REGISTRY_URI_PLACEHOLDER:5000/keptn/servicenow-service:latest
            imagePullPolicy: Always
            env:


---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: servicenow-sub
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: problem
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: servicenow-service


